### ISSUE TITLE
Configuration page won't allow webhook notification

### ISSUE THREAD

**Issue by jasedragon** [omise/graylog-plugin-slack-notification#1]
I'm having trouble getting the configuration page to accept my input. The only items I've configured are Title, Description, Webhook URL and Channel. 

Clicking 'Execute Test Notification' works and produces a test message in my slack channel.

Clicking the 'Create' button causes a popup 'Please fill out this field.' together with a highlight around the 'Slack Token' field. I'm not using slack tokens, nor is any field like 'Notify Users' or 'Add acknowledge button' configured.

The only way I can get the dialog to accept my configuration is if I add a dummy value in the 'Slack Token' field, but then my notifications do not work.

Versions: graylog v3.13 and graylog-plugin-slack-notification-3.1.0.jar

**Comment by KongZ** [comment]
@jasedragon I have remove required field from Slack Token. Please checkout 
https://github.com/omise/graylog-plugin-slack-notification/releases/tag/v3.1.1

**Comment by jasedragon** [comment]
Thanks for the quick response. This has resolved my issue, cheers!
