### ISSUE TITLE
Template message slack 

### ISSUE THREAD

**Issue by judika03** [omise/graylog-plugin-slack-notification#3]
I try to add templating message alert in graylog, not showing alert, Could you share your template graylog slack alert

**Comment by KongZ** [comment]
it does not support templating. It will work by just adding `Webhook URL`
If you want to format the alert, there are several options such as `Backlog Fields`, `Short Mode`, `Color`, `Footer Text`, `Footer Icon`, `Use pre-formatted text`, etc.

**Comment by judika03** [comment]
Thanks much your information.
I already setup graylog alert slack plugin, I found that error is double same backlog send to slack. Why?

**Comment by judika03** [comment]
I have problem that sending same backlog sending to slack, could you help me sir?

**Comment by KongZ** [comment]
Since you are open a new #4 i will close this one
