### ISSUE TITLE
URL incorrect in footer

### ISSUE THREAD

**Issue by calvinbui** [omise/graylog-plugin-slack-notification#8]
When clicking the source in the footer, the URL in the footer is incorrect.
```
https://graylog.example.com/messages/null/4a83cd20-7f7e-11ea-80b2-12513736edf2
```
should be

```
https://graylog.example.com/messages/graylog_0/4a83cd20-7f7e-11ea-80b2-12513736edf2
```

I think this has to do with the fact I'm running multiple nodes

**Comment by bosix** [comment]
I can confirm the error. Since we only run a single node I think it has nothing to do with that.

**Comment by KongZ** [comment]
Graylog changes API and remove the index name from Message. I will find a workaround.

**Comment by KongZ** [comment]
Release a new version fixing this issue
https://github.com/omise/graylog-plugin-slack-notification/releases/tag/v3.1.4

**Comment by bosix** [comment]
@KongZ works well. Than you for the fast solution.
